apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow
  process:
    matchPaths:
      - path: /usr/games/fortune
      - path: /usr/games/cowsay
      - path: /bin/bash
      - path: /bin/nc
    action: Allow
  file:
    matchPaths:
      - path: /etc/**  # Deny access to /etc files
    action: Audit  # Logs violation (Block for deny; Audit for demo log)
    matchDirectories:
      - dir: /app/
    action: Allow